#!/bin/sh
ver=$(cat version)
case $1 in
	start)
		if [ ! -f pybots.pid ]; then
			if [ -f pybots.pyc ]; then
				rm -rf pybots.pyc
			fi
			python pybots.py >> /dev/null &
			pid=$!
			echo $pid > pybots.pid
			echo "PyBots ($ver) started into background (PID: $pid)"
		else
			pid=$(cat pybots.pid)
			status="false"
			for data in $(ps | grep $pid); do
				status="true"
			done
			if [ $status = "false" ]; then
				rm -f pybots.pid
				sh pybots start
			else
				echo "PyBots ($ver) is already running"
			fi
		fi
		;;
	stop)
		if [ -f pybots.pid ]; then
			pid=$(cat pybots.pid)
			kill -9 $pid
			rm -f pybots.pid
			rm -f src/*.pyc
			rm -f modules/*.pyc
			if [ -f pybots.pyc ]; then
				rm -f pybots.pyc
			fi
			echo "PyBots ($ver) is stopped (PID: $pid)"
		else
			echo "PyBots ($ver) is not running"
		fi
		;;
	restart)
		if [ -f pybots.pid ]; then
			sh pybots stop
			sh pybots start
		else
			sh pybots start
		fi
		;;
	debug)
		while [ 1 ]; do
			if [ -f pybots.pyc ]; then
				rm -f pybots.pyc
			fi
			python pybots.py
			rm -f src/*.pyc
			rm -f modules/*.pyc
			if [ -f pybots.pyc ]; then
				rm -f pybots.pyc
			fi
		done
		;;
	update)
		available=$(curl https://raw.github.com/Pythonz/PyBots/master/version)
		version=$(cat version)
		if [ $available != $version ]; then
			running="false"
			if [ -f pybots.pid ]; then
				sh pybots stop
				running="true"
			fi
			git rm --cached database/*.db
			git add configs/*.conf modules/*.py
			git commit -m 'Save'
			git pull
			if [ $running = "true" ]; then
				sh pybots start
			fi
			echo "Done."
		else
			echo "No update available."
		fi
		;;
	status)
		if [ -f pybots.pid ]; then
			pid=$(cat pybots.pid)
			status="PyBots ($ver) seems to be crashed"
			for data in $(ps | grep $pid); do
				status="PyBots ($ver) is running"
			done
		else
			status="PyBots ($ver) is not running"
		fi
		echo $status
		;;
	*)
		echo "start | stop | restart | debug | update | status"
		;;
esac

